### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by ak-uk** [rubycas/rubycas-server#240]
Hi, 
I'm running Centos 7 without passenger, ruby 2.1.1

I get the standard login page but attempting to login throws an internal server error. 

This is when trying to use bundle exec and webrick

Output:

10.1.105.205 - - [06/Feb/2015:15:40:43 GMT] "GET / HTTP/1.1" 303 0
- -> /
10.1.105.205 - - [06/Feb/2015:15:40:43 GMT] "GET /login HTTP/1.1" 200 2363
- -> /login
NoMethodError - undefined method `first' for false:FalseClass:
	/var/www/html/cas/lib/casserver/authenticators/ldap.rb:106:in `find_user'
	/var/www/html/cas/lib/casserver/authenticators/ldap.rb:41:in `validate'
	/var/www/html/cas/lib/casserver/server.rb:426:in `block (2 levels) in <class:Server>'
	/var/www/html/cas/lib/casserver/server.rb:418:in `each'
	/var/www/html/cas/lib/casserver/server.rb:418:in `block in <class:Server>'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
[2015-02-06 15:40:56] ERROR NoMethodError: undefined method `join' for #<String:0x0000000281d1c8>
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
	/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
10.1.105.205 - - [06/Feb/2015:15:40:56 GMT] "POST /login HTTP/1.1" 500 356
https://10.1.220.49/login -> /login
^C

cat /var/www/html/cas/config/config.yml | grep -v ^# | grep -v ^$
server: webrick
port: 443
ssl_cert: /etc/httpd/ssl/apache.crt
ssl_key: /etc/httpd/ssl/apache.key
database:
  adapter: postgresql
  database: dbname
  username: user
  password: 'pass'
  host: localhost
  reconnect: true
authenticator:
  class: CASServer::Authenticators::LDAP
  ldap:
    host: ldap.domain.org.uk
    port: 389
    base: dc=domain,dc=org,dc=uk
    username_attribute: uid
    filter: (objectClass=person)
    auth_user: 'cn=user,ou=orgunit,dc=domain,dc=org,dc=uk'
    auth_password: 'pass'
theme: simple
organization: CAS
infoline: Powered by <a href="http://rubycas.github.com">RubyCAS-Server</a>
log:
  file: /var/log/casserver.log
  level: DEBUG

**Comment by ak-uk** [comment]
Rebuilding under passenger
